{1}{20}29.970
{50}{300}Preloil a upravil : Martin| etmare@atlas.cz
{3595}{3673}Do riti !
{4432}{4491}Bingo.
{8411}{8447}Do èerta !
{11895}{11955}Strie¾aj!
{12839}{12891}Prichádza!
{12947}{12999}- Vyskoè!
{13187}{13215}Áno!
{13430}{13456}Áno!
{13935}{14020}Nezdie¾am vašu rados...
{14034}{14147}- Dobrá práca, agentka Marcusová.|- Ïakujem.
{14150}{14265}Dobrá trefa, Mahoney.|Teraz vyèisti všetky tie sraèky, èo?
{14630}{14720}PIATOK 13 - part 9
{14720}{14900}PIATOK 13 - part 9|JASON IDE DO PEKLA
{14900}{15000}PIATOK 13 - part 9|JASON IDE DO PEKLA|Poslednı piatok
{15333}{15397}ID, prosím.
{15944}{16004}V poriadku, pane.
{17123}{17210}Meno - Voorhees, Jason.
{17210}{17323}Toto je iba na oèi. Táto páska|je striktne pre internú distribúciu.
{17327}{17393}Ak ste poèúvali viete, e znièi to môe|iba C-4 alebo nieèo silnejšie.
{17396}{17494}Ak nie - máte naozaj problém!
{18203}{18266}Ooh...
{18303}{18334}Boe !
{18688}{18781}Máme ve¾kého kaukazského samca ...
{18783}{18934}...s masívnou stratou tkaniva,|spôsobenou extrémne silnou trhavinou.
{18938}{19083}Váha - povedal by som 230, snáï... 240.
{19085}{19264}Tretí stupeò popálenín|na 65% predchádzajúceho trupu.
{19266}{19421}Prvı a druhı|na... neskoršom trupe.
{19993}{20088}K tej traumatickej explózii...
{20100}{20191}...subjekt je obe ...
{20194}{20265}...viacnásobnıch...
{20267}{20323}...strelnıch rán.
{20479}{20536}Na prvı poh¾ad, dá sa poveda...
{20539}{20606}...e sa pozeráme na nieèo okolo...
{20633}{20713}...stovky strelnıch rán...
{20776}{20853}...rozdielneho kalibru.
{20951}{21031}To je skutoène rados poèíta...
{21611}{21682}Take...
{21743}{21844}...pod¾a môjho profesionálneho názoru...
{21857}{21941}....je tento chlapík na sraèky !
{21973}{22072}- Hee!
{22075}{22145}Toto je posledná poznámka v zázname.
{23221}{23367}Ako ïalší dôkaz,|je tu indikácia p¾úcneho edému.
{23455}{23592}Povedal by som, e srdce sa zdá by|dvakrát väèšie ako normálne srdce.
{23592}{23685}Je znetvorené.
{23715}{23823}Ve¾ké usadeniny v pravej,|aj ¾avej komore.
{24071}{24229}Srdce sa zdá by preplnené|èiernou, viskóznou tekutinou.
{24321}{24441}Jednoducho neviem, èo do pekla to je.|Ale krv to nie je.
{27150}{27201}ID!
{27203}{27312}- Veï ste videli, e vychádzam odtia¾.|- ID, prosím.
{27606}{27669}Ach! Poèkajte chví¾u.
{27831}{27918}To šteklí!
{28339}{28466}Vieš Phil, toto je skutoène|úasná príleitos.
{28469}{28640}Ko¾ko ¾udí môe poveda, e sa dostali|a k skurvenému Jasonovi Voorheesovi?
{28689}{28768}Hej, do prdele!
{28771}{28920}Èo to robíš, ty debilnı,|idiotnı magor?
{28923}{28976}Skús toto!
{28979}{29080}Tak skús to.|Vieš èo by som ti najradšej urobil?
{29090}{29201}Najradšej by som a rozrezal|priamo cez tvoju skurvenú masku.
{29204}{29316}Starı, dobrı, hrubı rez.
{29380}{29454}Áno... to by som urobil.
{29697}{29741}Phil!
{30112}{30238}Tak doktor, ako to dopadlo?|Postaví sa Jason èoskoro na nohy?
{30240}{30323}Skutoène pochováme toho pankharta.
{30391}{30478}Aj tak nie je niè,|iba ve¾ké odporné hovno.
{30482}{30561}Dnes veèer - American Casefile.
{30564}{30661}Jason Voorhees - màtvy alebo smrtiaci?
{30664}{30775}Tieto zábery sú pár minút|po pitve Jasona Voorheesa.
{30783}{30903}Fakty?|Dvaja mui z ochranky - màtvi.
{30909}{30968}Ohliadaè màtvol - màtvy.
{30974}{31063}Druhı ohliadaè màtvol - nezvestnı.
{31066}{31194}Sú títo mui obeami masového vraha,|o ktorom si mysleli e neije?
{31196}{31227}Väèšina tvrdí, e áno.
{31306}{31346}Dobrı veèer, som Robert Campbell.
{31349}{31476}Viac ne 20 rokov staèilo iba vyslovi|meno Jason Voorhees...
{31478}{31591}...a srdcia ¾udí sa rozochveli strachom.
{31594}{31693}Narodenı v roku 1946|Eliášovi a Pamele Voorheesovcom...
{31696}{31843}...všetci verili, e sa Jason utopil v tábore|Crystal Lake vo veku jedenástich rokov.
{31846}{31910}Zdá sa, e nie.
{31912}{32017}Od tej doby bol zodpovednı|za 83 potvrdenıch vrád...
{32020}{32086}...a hovorí sa o vyššom poète.
{32088}{32224}Dnes veèer v špeciálnom vydaní|American Casefile...
{32226}{32298}...vám poskytneme rozhovor|s Creightonom Dukom...
{32301}{32396}...jeden tıdeò po|Jasonovom neskutoènom konci.
{32399}{32463}Upozoròujem, e pán Duke|je naozajstnı lovec...
{32463}{32614}...zodpovednı za dolapenie šiestich najviac|h¾adanıch masovıch vrahov.
{32616}{32665}Pusme si záznam.
{32677}{32832}Po prvı krát v histórii, dostali naše|kamery monos zachyti tvár...
{32835}{32890}...lovca Creightona Duka.
{32892}{33032}Duke nás prijal pod podmienkou ve¾mi|neobyèajného, ve¾mi zaujímavého návrhu.
{33032}{33130}A myslím e budete súhlasi, keï poviem,|v typickom Creighton Dukovskom štıle...
{33130}{33243}...nám poskytol ove¾a viac,|ne sme poèítali.
{33245}{33297}Presveète sa sami.
{33311}{33356}Chcem vám poveda dve slová...
{33358}{33451}...a chcem aby ste povedali prvú vec,|ktorá vás napadne. Dobre?
{33453}{33501}- Dobre.|- Ste pripravenı?
{33503}{33560}- Poïme.|- Jason Voorhees.
{33616}{33712}Dobre, napadá mi...
{33715}{33835}...dievèatko v ruovıch šatách,|miešajúce hot dog s koláèom.
{33915}{34018}Akurát som hovoril o vašom vyhlásení,|e Jason Voorhees nie je skutoène màtvy.
{34061}{34168}Èo si myslíte o Jasonovi...|Jason neije.
{34186}{34274}To telo, ktoré nosí - to je iba mäso.
{34276}{34359}Ten chlapec vie, ako sa obliec.
{34362}{34465}Nosí telá inıch ¾udí,|tak ako ¾udia nosia šaty.
{34468}{34565}Môete do neho k¾udne streli,|no jemu to nevadí.
{34568}{34635}Ako keby si zobral iné telo.
{34652}{34771}Jason Voorhees,|skutoènı Jason Voorhees...
{34776}{34890}...je nieèo, èo ste vy, ani ja|nikdy predtım nevideli, pán Campbell.
{34892}{35023}Je iba jedinı spôsob,|ako s ním skoncova na veèné èasy.
{35025}{35164}A ja som jedinı, kto ten spôsob pozná.
{35174}{35296}Take, ak ho chcete ma màtveho,|naozaj màtveho...
{35319}{35404}...$500,000 je moja odmena.
{35404}{35533}A za to dostanete masku,|maèetu, celú tú prekliatu vec.
{35540}{35617}- To je charakter...
{35649}{35734}V nasledovnom tıdni|po našom rozhovore s Creightonom Dukom...
{35734}{35829}...nasledovalo pä vrád|v Jasonovom štıle.
{35829}{35900}Všetky, èo nás neprekvapuje...
{35904}{35986}...na ceste z federálnej márnice|v Youngstown, Ohio...
{35986}{36110}...kde boli Jasonove pozostatky...|...do Crystal Lake.
{36118}{36213}Dnes veèer...|v záujme verejnej bezpeènosti...
{36216}{36334}...som pripravenı ponúknu Creightonovi Dukovi|jeho $500,000,
{36337}{36479}splatnıch len potom, ako poskytne pre|American Casefile a americkı ¾ud...
{36482}{36574}...nespornı dôkaz o|Jasonovej existencii...
{36574}{36696}...a následne s ním skoncuje na veèné èasy.
{36696}{36807}Èoskoro sa s American Casefile|vrátime...
{37218}{37289}- To je fakt choré.|- To mi rozprávaj...
{37293}{37373}Nie, to nie je choré, Diana.|To je biznis.
{37375}{37484}¼udia sa doslova pohrnú, aby si pozreli,|kde bıval obávanı Jason.
{37487}{37574}- Di, jedlo je hotové.|- Ïakujem, Shel.
{37576}{37685}Hej mama, naozaj chceš|aby som to krájal takto?
{37688}{37754}- Áno, chcem.|- Vyzerá to debilne.
{37758}{37886}To je chyba tvojej debility.|¼udia sa chcú pozera na hokejovú masku!
{37919}{37980}Teraz sa pozeraj.
{38099}{38199}Takto sa robí nová plnená placka.|Hence, dva-v-jednom burger predaj.
{38202}{38299}Boe, ako milujem túto enu.|Dr sa odo mòa ïalej!
{38301}{38380}Chlapci, je mi z vás naniè.
{38565}{38625}Èo vám môem ponúknu?
{38627}{38743}Poprosím Voorhees burger|a pár Jason prstov.
{38760}{38827}Dobre, ešte nieèo?
{38829}{38848}Áno.
{38910}{38971}Creighton Duke.
{38992}{39047}Viem kto ste.
{39053}{39145}Idem zabi Jasona Voorheesa.|Potrebujem vašu pomoc.
{39156}{39194}Jason Voorhees je màtvy.
{39230}{39323}Vy viete, e nie je...|Ja viem, e nie je...
{39325}{39375}A prichádza pre vás.
{39385}{39438}Vaše jedlo tu bude hneï.
{39446}{39503}Povedzte si cenu.
{39506}{39600}Kadı má cenu. Aká je tá vaša?
{39608}{39702}- Èo chcete?|- Vy viete, èo chcem.
{39705}{39749}A viete, preèo vás potrebujem.
{39797}{39848}Myslím, e potrebujete odís.
{39851}{39971}Viem o vás všetko, Diana.|Viem, kto naozaj ste.
{39973}{40012}Èo je tu za problém?
{40015}{40142}Iba som dal vášmu dievèau|malı návrh, šéfe...
{40145}{40182}... a ona nad tım premıš¾a.
{40191}{40238}Naozaj, miláèik?
{40247}{40273}Vypadnite.
{40313}{40377}Preèo ma neudriete, šéfe. Mm?
{40380}{40438}Vaše dievèa by sa potešilo.
{40549}{40617}Je to moje dievèa, o ktorom hovoríte.
{40617}{40715}Vidím, e je iba vaša, pretoe...
{40718}{40781}...neskúsilo doteraz Duka.
{40784}{40884}- Dobre, do pekla!|- Opatrne, opatrne, šéfe.
{40898}{40963}Nemyslím, e naozaj viete kto som.
{40965}{41023}Viem kto ste.
{41026}{41148}Posledné èo tu potrebujeme, je nejakı|podvodnı lovec, spôsobujúci problémy.
{41152}{41237}Chcem aby ste odišli z tohoto mesta|a chcem, aby ste to urobili hneï.
{41240}{41343}- Teraz ste sa vyfarbili, šéfe.|- Randy!
{41380}{41466}Vezmi ho von k môjmu autu.|Budem tam o chví¾u.
{41469}{41518}V poriadku, poïme.
{41520}{41618}Príde si pre vás, Diana.|A pre vašu dcéru.
{41620}{41681}Zamknite si dvere.
{41748}{41795}Mrzí ma, e a nahneval.
{41802}{41933}Nepotrebujem, aby si za mòa bojoval.|Nepotrebujem ochranu na poloviènı úväzok!
{41984}{42026}Si v poriadku?
{42028}{42128}- Áno.|- Dobre.
{42130}{42229}Zdá sa, e myslíš e Jason si pre teba príde.
{42250}{42312}Stephen, potrebujem s tebou hovori.
{42321}{42466}Je nieèo, èo nevieš o Jessice.|Nieèo, èo by si mal vedie.
{42469}{42588}Chcela ti to poveda u dávno,|ale nikdy nebolo dos èasu.
{42592}{42707}Ak máš stále o òu záujem, ak stále chceš,|aby sa problémy medzi vami urovnali...
{42710}{42769}...mali by sme sa pozhovára.
{42771}{42831}Dobre, pozhovárajme sa.
{42833}{42896}Áno, ale nie tu.
{42896}{43039}Príï ku mne dnes veèer o jedenástej.|A buï presnı.
{43531}{43593}Ou!
{44197}{44260}Vıborne!
{44262}{44281}Ahoj.
{44297}{44403}Ve¾mi pekne ïakujeme.|Boli sme tu celú hodinu.
{44405}{44461}Naozaj ïakujeme, èloveèe.
{44482}{44561}Take... kam ideme?
{44563}{44619}Ideme do tábora v Crystal Lake.
{44622}{44649}Oh, fakt?
{44654}{44825}Plánujete veèery pri ohni,|predmanelskı sex a by zabití?
{44944}{45071}Iba artujem. Bol to iba vtip.|Srandièky o Crystal Lake.
{45127}{45231}- No, preèo idete do tábora?|- Teraz keï je Jason màtvy...
{45234}{45315}Plánujeme veèery pri ohni,|predmanelskı sex...
{45315}{45416}...a, netrápime sa tım,|e budeme zabití.
{45588}{45712}Toto je miesto, kde bol tábor.|Chatky zbúrali, ale toto je to miesto.
{45715}{45785}Vıborne!
{45802}{45868}Hej, fakt ïakujeme.
{46055}{46108}Poï s nami.
{46111}{46171}O dipovaní porozmıš¾ame neskôr.
{46220}{46307}Boe. Ve¾mi rád...
{46310}{46384}...ale, um, mám sa s niekım stretnú.
{46413}{46501}Oh... tvoje dievèa?
{46541}{46604}Choï u a zabavte sa.
{46753}{46819}Nevieš o èo prichádzaš.
{47437}{47495}Tak poïme.
{47936}{48013}Oh Boe, tá voda.
{48780}{48810}- Um...
{48820}{48930}... nebude ti vadi, keï pouijeme stan|tak na pol hodiny?
{48933}{49042}Nie, nie, skutoène. Vezmite si ho na|celú noc, ja budem spa vonku.
{49045}{49115}- Áno?|- Áno. Myslím, e bude krásna noc.
{49117}{49241}- Urèite?|- Jasné. Áno, urèite. Choï... be ! Be !
{49246}{49320}Be, be, be...
{50616}{50689}Do èerta !
{52745}{52814}Oh, to je super.
{52832}{52900}Myslíš, e si pripravená|na Tony the Wonder Llama?
{52902}{52969}Máš pripravenú gumu?
{52975}{53076}V mojom batohu vonku.
{53096}{53172}- Skoèím pre òu.|- Nie! Nie, nie, nie,...
{53172}{53265}Zabudni na to. Zabudni na to.
{53353}{53425}Aj tak potrebujem èúra.
{53459}{53565}Aj tak musím ís von.|Za chví¾u som spä.
{53567}{53619}Oh!
{53622}{53682}Ponáh¾aj sa!.
{55174}{55253}- Našla som to.|- Áno?
{55256}{55345}- To je super.
{55389}{55470}Oh Boe, Debbie, nenávidím tieto veci.
{56776}{56882}- Debbie! Pomoc!
{58873}{58976}- Tango! Tango?
{59088}{59231}- Oh, tu si. Dobre, poï sem.
{59242}{59349}Tu. Áno.
{59354}{59457}Och, miláèik, tu si. Áno.
{60288}{60359}- Di, to som ja, Josh.
{60362}{60471}Ja... Iba som išiel do auta.|Nechcel som a na¾aka.
{60474}{60566}- Tu.|- To je v poriadku.
{60569}{60647}Ach, ïakujem.
{60651}{60716}Pozri miláèik...
{60733}{60822}...netráp sa kôli Edovi,|bude niekde nablízku.
{60824}{60901}Je dos bystrı na to,|aby sa nestratil, veï vieš...
{60904}{60998}Stále si myslím, e som ešte mladá,|no som u asi stará...
{61000}{61150}Ale on to ve¾mi dobre vie.|Ver mi... pracuje sa na tom.
{61198}{61284}- Ïakujem.|- Dobrú noc.
{61287}{61371}Dobrú noc, Josh.
{61531}{61617}Ahoj, zlatko.
{61620}{61669}Tu nie. Ach prepáè, idem neskoro.
{61671}{61750}A to je problém?|Bude vadi, e prídeme neskôr?
{61753}{61887}Liga zmenila ten prekliaty èas,|take staèí keï tam budeme 10:30.
{61902}{61955}- Prestaò!
{64305}{64347}Do prdele!
{64399}{64441}Èo to kurva robíš?!
{64445}{64497}Ty hajzel!
{65098}{65178}- Haló?|- Ahoj, mami.
{65180}{65273}- Ahoj.|- Vieš èo je nové? Mám nového priate¾a.
{65275}{65342}- Neuhádla by si koho.|- Dobre, ako sa volá?
{65344}{65425}- To bude prekvapenie.|- Och, niekto koho poznám?
{65428}{65519}Nie, ale spoznáš ho.
{65521}{65659}Prídeme a pozrie budúci víkend.|Naozaj sa teší na stretnutie s tebou.
{65664}{65749}- Môeš sekundu poèka?|- Jasné.
{66153}{66173}Ahoj.
{66177}{66296}- Ako sa má malá?|- Vıborne. Nevidela si náhodou jej otca?
{66299}{66402}- Steven príde a veèer.|- Mami!
{66405}{66476}- Stále sa na teba pıta.|- Ja s ním nechcem hovori.
{66490}{66593}Nechcem ho vidie, keï som doma.|Môe vidie diea, kedy len chce.
{66598}{66658}Môeš mu to poveda?
{66661}{66727}- Poviem mu to.|- Milujem a, mami.
{66733}{66827}Tie a milujem, miláèik. Um...
{66938}{66963}Mami?
{67016}{67115}Èo robíš? Josh!
{67121}{67157}Och, Boe !
{67194}{67261}Nie!  Nie!
{67475}{67531}Ty skurvenı...
{67536}{67603}- ...pankhart!
{67720}{67797}Áno, ahoj. Je tam šerif Landis?
{67822}{67911}Tu je Jessica Kimble.|Mohli by ste ma prepoji?
{68891}{68930}Nie!
{68934}{68996}Nie!
{69033}{69079}Diana?
{70135}{70182}- Oh, do riti !
{71272}{71368}Videl si ho.
{71371}{71447}Vieš kto to je?
{71478}{71558}Musíš zachráni Jessicu.
{71561}{71669}Zachráò Jessicu a ...
{71683}{71750}A èo?!
{71752}{71835}Zachráò Jessicu...
{71838}{71899}...a...
{71933}{71998}- Diana?
{72145}{72202}Bol to Josh.
{72205}{72246}Je stále vonku...
{72344}{72377}Kde do pekla je?
{72380}{72486}Ach... dobrotivı boe.
{72492}{72549}Veï bol màtvy. Mal by by màtvy!
{72913}{72983}Hádam si nemyslíš, e ... ?
{73158}{73272}Neverím, e si zavradil Dianu.|Neviem, èo sa stalo.
{73274}{73351}Ale ja viem, e si to nemohol urobi.
{73449}{73510}Trváš na tom, èo?
{73512}{73577}Všetko sa vysvetlí.
{73617}{73688}Randy, èo budeme robi ?
{73756}{73830}Èo bude s Jessicou ?
{74645}{74795}Jessica! Ja... ve¾mi ¾utujem. Chcela som to|uprata, predtım ako prídeš.
{74798}{74839}To je v poriadku. Ja som iba...
{74920}{75026}- Ach, Boe...
{75385}{75440}Ach, boe !
{75548}{75607}Kto je to?
{75717}{75771}Dievèa?
{75774}{75856}Je krásna.
{75858}{75894}Je tvoja?
{75912}{75986}Volá sa Stephanie.
{76014}{76066}- Má oèi po Stevenovi.
{76150}{76199}Preèo si mi to nepovedala?
{76209}{76318}Chcela som. Chcela som to poveda|všetkım, ale jednoducho...
{76334}{76421}Neèakala som, e sa vrátiš tak skoro.
{76423}{76462}Je tu niekde Steven ?
{76728}{76889}Poèúvaj, je... Je tu nieèo,|èo ti musím poveda o Stevenovi.
{77027}{77102}Dúfam, e a tu nebudeme|dra viac ako deò.
{77106}{77194}Riskujem vlastnú ri|keï verím, e si nevinnı.
{77196}{77347}Ale musíš by k¾udnı,|inak a Landis zabije, jasné?
{77579}{77645}Poï.
{77668}{77755}Sheriffova kancelária je tam.
{78194}{78302}V poriadku, vrátim sa neskôr.|Neurob iadnu hlúpos.
{78302}{78403}Èo by som mohol urobi ?|Som zatvorenı v blbej cele.
{78405}{78479}Dostanem a odtia¾to,|ale bude to tesné.
{78565}{78631}Dobre.
{78859}{78955}Och, poèkaj.|Všetko èo potrebuješ, je v tejto taške.
{78957}{79049}- Dobre.|- Biela f¾aša: o dvanástej.
{79054}{79175}- Zelená f¾aša: o pol druhej.|- A nejakı likér v èase obeda(?)
{79177}{79234}Neboj sa.
{79279}{79323}A o ko¾kej si ju prídeš zobra?
{79327}{79397}Um... prídem veèer okolo ôsmej.
{79401}{79522}OK. Ahoj miláèik. A nie e|budeš Vicki trápi. Ahoj.
{79524}{79596}Ïakujem, Vicki.
{79614}{79677}Hej, dobre sa o òu staraj.
{79677}{79803}- Samozrejme.|- Jessie, mám tu zopár papierov...
{79805}{79915}- ...potrebujem ich podpísa.|- Jasné.
{79939}{80113}Ty naozaj vyzeráš ako ten|najhroznejší sadista, akého som kedy videl.
{80115}{80175}Dr u koneène hubu !?
{80192}{80251}Obvinenı z vrady.
{80254}{80406}A nie hocijakej vrady, ale vrady|matky dievèaa, ktoré miluješ.
{80416}{80471}Neurobil som to.
{80478}{80559}Och, ja viem. Problém ale je,
{80561}{80678}ako to urobi,|aby uverili aj ostatní?
{80786}{80858}Bol to Jason, kto zabil Dianu.
{80892}{80941}Èo si to povedal?
{80945}{81053}Je iba jeden spôsob,|ako skoncova s tım diablom.
{81087}{81150}A oni ho nepoznajú.
{81255}{81319}A ty vari áno?
{81393}{81509}- Tak hovor!|- Takáto informácia... je ve¾mi drahá.
{81519}{81646}- A èo za to chceš?|- Na to si príliš zbabelı.
{81741}{81806}Skúsme to.
{82121}{82181}Podaj mi ruku.
{82226}{82309}- Èo?|- Tvoju ruku...
{82312}{82356}...podaj to ju.
{82615}{82651}Vidíš...
{82663}{82765}...všetci a všetko...
{82767}{82831}...má svoju cenu.
{82842}{82934}A cena za toto je ve¾mi, ve¾mi vysoká.
{82981}{83040}Si pripravenı zaplati?
{83140}{83252}- Aká je cena?|- Si pripravenı zaplati?
{83334}{83358}- Áno.
{83547}{83627}- Au! Do prdele!
{83929}{84045}Jedinı spôsob, ako zabi Jasona|Voorheesa, je znièi jeho srdce.
{84048}{84150}A je tu u iba jediná taká osoba,|keïe je Diana màtva.
{84152}{84215}Jej dcéra.
{84218}{84318}- Jessica?|- A on sa bude pokúša dosta k nej prvı.
{84323}{84401}- Dobre, tak èo teda chce?|- To isté, èo chcel od jej matky.
{84409}{84465}Èo?
{84524}{84581}Chceš informáciu...
{84621}{84654}...musíš zaplati.
{84741}{84790}No tak!
{84796}{84833}Tvoju ruku.
{85042}{85108}- Si pripravenı zaplati?|- Áno.
{85122}{85221}- Si si istı?|- Áno!
{85284}{85379}-  Ooh, Boe !! Ow.
{85500}{85616}Tí idioti z FBI znièili Jasonove telo,|take teraz potrebuje nové.
{85619}{85699}Tí, ktorí majú šancu zmeni si telo,|tí sa nestratia.
{85702}{85780}Dostanú chorıch, dostanú slabıch.
{85783}{85886}Jason sa potrebuje znova narodi|a na to potrebuje Jessicu.
{85890}{85931}Preèo Jessicu?
{85965}{86101}Tak toto, zdá sa, je ve¾mi, ve¾mi|drahá otázka, chlapèe.
{86104}{86262}A... nemyslím, e máš na to,|aby si to zaplatil.
{86367}{86439}Hovor.
{87145}{87197}Je to v dome.
{87275}{87429}Tam kde sa Voorhees narodil,|tam sa Voorhees môe znova zrodi.
{87443}{87533}A jedine rukou Voorheesa|môe zomrie.
{87556}{87616}Jason má sestru...
{87629}{87716}...matku tvojho dievèaa, Dianu.
{87729}{87794}Teraz, keï je màtva...
{87794}{87942}...sú iba dve pokrvné príbuzné na svete,|ktoré ho dokáu zabi,
{87946}{88026}alebo znovuzrodi.
{88030}{88089}Jessica a jej diea.
{88103}{88159}Musím sa odtia¾to dosta.|Musím ich ochráni.
{88162}{88358}Jedinı spôsob je zabi Jasona|a to nemôeš ! Ale Jessica môe.
{88363}{88468}Povedz Jessice pravdu o jej dieati.|A sna sa ju presvedèi.
{88470}{88537}Choï do Voorheesovho domu.|Nájdi dôkaz.
{88544}{88637}Pretoe ak nie, Jason ju zabije...
{88639}{88684}...a vaše diea tie.
{88764}{88835}Randy! Randy!
{88876}{88936}Agh! Boe.
{88939}{89047}- Èo to do pekla robíš?|- Tento sukin syn mi zlomil prsty.
{89049}{89159}- Boe ! Do prdele!|- Uká mi to, OK? Tu.
{89266}{89337}- Do riti !
{89371}{89434}Ticho.
{89437}{89495}Ty kretén.
{89498}{89540}OK...
{89543}{89684}...opatrne, opatrne, otvor celu.
{89697}{89777}Ty by si ma nezabil.
{89779}{89854}Mono máš pravdu.
{89939}{90020}Dobre, Steven.
{90328}{90426}Steven... poèúvaj ma, prosím.
{90448}{90574}Nerob to.|Ak uteèieš, zastrelia a.
{90735}{90833}Ale je šanca, e sa mi to podarí.
{90874}{90942}Na dnes mám dos...
{90945}{91002}Zavia to.
{91004}{91079}Milujem túto malú dámu.
{91081}{91178}Nerob sa tak noblesná. Mali by sme|zatvori, kım nebude po pohrebe.
{91180}{91283}- Jasné. Dva dni neplateného vo¾na, e?|- Hej, miláèik. Teraz nie.
{91286}{91423}Ver mi alebo nie, tie mi to zrovna|nevyhovuje. A èo do riti je toto?
{91428}{91541}- To je Jessicine diea.|- Daj ho niekde do prdele. Toto nie sú jasle.
{91550}{91725}Hej. Veï je to tá najkrajšia vec,|akú kedy boh poslal na zem.
{91727}{91834}- Ty malı maznáèik.|- To bude, keï ho vyhodím na ulicu.|U nech je preè!
{91896}{91974}Áno? Áno.
{91995}{92066}Naozaj?
{92148}{92217}Áno, áno, áno. Áno.
{92219}{92285}Áno. Ak ho uvidím, zavolám.
{92287}{92337}Dobre.
{92341}{92399}- Èo to zase bolo?|- Hej, diea môe osta.
{92401}{92549}Choï do skladu a urob mu z nieèoho|poste¾. Choï, choï, choï !
{92623}{92785}- Steven Freeman unikol. Má zbraò.|- Pre boha. Vedia, kam má namierené?
{92796}{92911}Ako poznám Freemana,|zmizne niekam do Kanady.
{92914}{92981}Ale ak náhodou nie...
{92984}{93070}- Hej, nechaj to na mòa.
{93185}{93220}- Oh!
{93253}{93297}Pre boha, Pookie.
{93460}{93543}OK, tu máme medvedíka.
{93545}{93636}Viem e to nie je palác,|ale nejako to vydríme.
{93638}{93731}O boe, vyzeráš celkom ako tvoj otec.
{93771}{93847}OK... dáme a sem.
{93850}{93991}Za chví¾u a prídem pozrie,|èi si v poriadku. Dobre?
{94553}{94620}Och, boe.
{94623}{94707}Veï ja ani neviem, ako sa voláš.
{94743}{94809}Steven.
{94856}{94923}Toto je... moje diea.
{95009}{95116}Je to prvı krát, èo sa môem|dotknú svojho dieaa.
{95253}{95310}Vezmi si moje auto. Choï u.
{95312}{95392}- Ale ja...|- Choï u.
{95427}{95469}Ïakujem.
{96057}{96127}Ach, Boe.
{97328}{97386}Ach, môj... !
{99018}{99070}- Nie!
{100518}{100557}Oh?
{100560}{100637}Hej Reggie, èo sa stalo?
{100641}{100748}Oh áno, teraz som tu.|To je vıborné, strašidelné.
{100750}{100893}Pozri sa, potrebujem sa obliec. Môeme|da nejaké kusy do chladnièky?
{100895}{100976}Dobre, Reg, porozprávaj sa s Harrym.
{100979}{101034}Vieš preèo som sem prišiel...
{101037}{101121}... tajomstvo domu Voorheesovcov|je odhalené.
{101124}{101158}Ach, a ešte...
{101162}{101198}...ešte jedna vec.
{101203}{101308}Hádaj, èo budeš zajtra èíta na|titulnıch stránkach novín?
{101360}{101499}Telo Voorheesom zabitej eny|ukradnuté z márnice.
{101502}{101654}Take, vèera veèer som ukradol Dianine telo|a ukryl som ho tu na záchode.
{101656}{101767}A potom som išiel domov|a pretiahol som jej dcéru.
{101828}{101874}Reg.
{101896}{101955}Reg, Reg, uk¾udni sa.
{101958}{102072}Poèúvaj, povedal som Jessice,|e nás nájde tu, dobre?
{102075}{102170}Ja privolám políciu,|nájdu telo...
{102170}{102240}...a naša odmena|unikne posratım komínom!
{102244}{102293}Ako to urobi, aby a chytili?
{102352}{102391}Boe ! Aagh!
{106539}{106581}Robert?
{106930}{106995}Hello?
{109504}{109602}Nenormálne si ma vystrašil.|Kde si bol?
{109602}{109671}- Robert!
{109709}{109771}Zmizni od nej!
{109782}{109846}Èo... èo to pre boha robíš?
{109848}{109973}- Rıchlo!|- Èo? Môj Boe! Steven, pusti ma.
{109975}{110059}Nikam s tebou nejdem.|Zabijem a!
{110062}{110130}Okamite ma pusti.|Zabijem a!
{110133}{110238}- Ach!|- Nastúp do auta. Nastúp do auta!
{110238}{110329}Èo sa deje? Èo sa pre boha stalo?
{110333}{110368}- Tak odpovie mi niekto?|- Dr hubu !!
{110523}{110545}Do riti.
{110605}{110742}Ach! Ach! Ach, môj Boe.
{111240}{111328}- Pre boha, Steven!
{111442}{111593}Zastav to auto !|Steven, myslím to váne! Zastav to auto!
{111681}{111758}- Èo ti to napadlo?!|- Buï u ticho. Zavri u hubu!
{111762}{111814}Prosím. Iba ma vypoèuj.
{111819}{111921}Dobre. Teraz si myslíš,|e som zabil Roberta, však?
{111926}{112065}A v iadnom prípade neije?|No povedz, zabil som ho, èi nie?
{112070}{112129}- Áno, zabil si ho.|- Omyl.
{112134}{112201}Nie je màtvy,|ba dokonca to nie je Robert.
{112204}{112302}Jess, nezabil som tvoju matku.
{112306}{112439}Vèera, Josh, alebo niekto|kto vyzeral ako Josh, ju zabil.
{112442}{112500}Stalo sa to potom,|ako ho udrela do hlavy.
{112503}{112599}Prepichol som mu srdce|a ten sukin syn stále il.
{112602}{112641}Steven, prosím, dovo¾ mi odís.
{112641}{112737}Ty a diea ste v nebezpeèí.|Môem vám pomôc.
{112767}{112805}Tentokrát a neopustím, Jess.
{112810}{112925}- Ale áno, Steven.|- S¾úbil som, e nie.
{112998}{113094}Jess... choï pre diea.
{113179}{113266}Zasranı blbec!|Zabil si mi matku a myslíš si,|e a pustím k svojmu dieau?!
{113272}{113404}- Zmizni! Vypadni!|Choï odo mòa preè!
{113408}{113475}- No tak!
{113478}{113529}- Jess, prosím!|- Choï odo mòa preè!
{113533}{113625}- Zmizni!|- Jess! Jess!
{113628}{113701}Do èerta. Nie! Nie.
{113907}{114045}Ed! Ed! Práve som utiekla Stevenovi|z jazernej cesty. Zabil Roberta!
{114048}{114148}- Spoma¾. Si v poriadku?|- Zabil ho. Bola som v matkinom dome...
{114152}{114233}- Ublíil ti?|- Nie mne. Robertovi!
{114235}{114349}- Hovoríš, e je na jazernej ceste. Kde?|- Ja neviem.
{114352}{114508}- Niekde na Meyerovom pozemku.|- Dobre, dostaneme ho. U si v bezpeèí.
{114510}{114594}Pošlite všetky jednotky na jazernú cestu.|Chcem toho chlapíka.
{115025}{115075}Nestrie¾aj. Nestrie¾aj.
{115139}{115159}Oh, Randy.
{115211}{115275}Sukin syn!
{115416}{115484}Serem na teba!
{115675}{115771}- Hej, si v poriadku?|- Agh!
{116083}{116143}O boe. Ach!
{116165}{116270}- Nastúp do toho posratého auta, Steven.
{116293}{116347}Ty nastúp do auta!
{116350}{116410}Chceš aby som ti ublíil?
{116413}{116487}Myslíš si, e môeš robi,|èo sa ti zachce?
{116490}{116554}Mám zbraò!
{116557}{116602}Poser sa.
{116604}{116650}Mám zbraò.
{116717}{116756}Úplne si vystrašil Jessicu.
{116794}{116875}- Jessica. Videl si Jessicu?|- Áno, videl som Jessicu.
{116885}{116919}Kde je?
{116945}{116980}Na stanici.
{117026}{117065}Udri ma.
{117070}{117112}Udri ma!
{117178}{117282}Randy práve dostal Stevena.|Vezie ho sem.
{117282}{117358}Jessica, choï s poruèíkom Ryanovou.|Dá ti nejaké šaty.
{117362}{117433}Jediné èo máme, sú uniformy.
{117435}{117461}To je v poriadku.
{117517}{117583}Moment.
{117589}{117658}Ste v poriadku, pane? Poèkajte chví¾u.
{117660}{117707}Èo to ... ?
{117805}{117891}Nájdite ju a nájdite ju rıchlo.
{117893}{117961}- Dobre. Budem tu èaka.
{118336}{118401}- Okamite prestaò!
{118726}{118799}Steven, pomô mi!
{118819}{118857}Jessica!
{118963}{119024}Uhni !
{119518}{119585}Èo to do pekla bolo?
{119677}{119737}Zranenı dôstojník !
{119741}{119794}Dıcha.
{119797}{119881}Nech ide jeden èlovek na koniec chodby.
{119884}{119925}Do prdele!
{119930}{120010}Boe!
{120056}{120089}Zavolaj sanitku.
{120368}{120433}Ach, kurva! Ach, kurva!
{120518}{120586}Agh!
{121119}{121168}- Vick, kde je diea?|- Je v poriadku.
{121170}{121237}- Kde je diea?|- Je vzadu.
{121239}{121298}Hej !! Odstúp.
{121300}{121362}Ani sa kurva nehnite,|ani jeden.
{121364}{121381}Joanne...
{121383}{121474}Dr hubu! Si s ním.|Nedoijete sa budúceho rána.
{121477}{121608}- Pookie, volaj na stanicu.|- Ako povieš miláèik, ako povieš.
{121610}{121661}Skurvená robota.
{121664}{121735}Linka je hluchá.
{121738}{121854}Sukin syn. Ward, choï a pozri sa,|èo sa deje na stanici.
{121857}{121953}- Nenechaj ho odís. Zabije ho.|- Dr hubu !! A ty choï.
{121953}{122009}- Mami, ale ja...|- Ward!
{122012}{122144}- To si zober pre prípad.|- Whoo!
{122219}{122331}- Zlatko, dávaj si pozor.|- Mami!
{122333}{122471}- Ward, nerob to. Prosím.|- Dr hubu! Drte ruky hore - vysoko.
{122513}{122547}Mám a!
{122556}{122612}Mám a!
{122833}{122921}Joey, prosím.|Nechaj ma zobra diea a odís.
{122923}{123026}- Dr tú zasratú hubu. Si so zloèincom.|- Hej, dávaj si pozor na jazyk.
{123030}{123092}- Serem na teba!
{123226}{123317}- Teraz sa pozri, èo si kurva urobila!|- Daj mi to diea, Joey!
{123317}{123391}- Serem na teba!
{123394}{123420}Prepáè.
{123448}{123492}Stoj ! Myslím to váne.
{124854}{124889}- Poï!
{124889}{124922}Je preè.
{124924}{124995}- Kde je ?|- Musela ju odnies Vicki.
{124995}{125066}- Tadia¾to. Poï.
{125970}{126051}Musí by tu.
{127447}{127515}Ach boe, Vick.
{127711}{127754}Skúsim zohna nejakú pomoc.
{128214}{128235}Do prdele.
{128308}{128362}Jessica!
{128400}{128440}Jessica, poèkaj!
{128441}{128516}Kurva! Do prdele.
{128944}{129084}Mám tvoje diea.|Príï do Voorheesovho domu. Sama.
{129692}{129734}Boe.
{130062}{130113}Si sama?
{130116}{130172}Dobré dievèa.
{130175}{130312}Jason mohol prejs do kohoko¾vek|a teda aj do teba.
{130336}{130424}Take formality máme za sebou.
{130427}{130476}Volám sa Creighton Duke.
{130478}{130616}Èo do pekla si myslíš, e robíš?|Ukradneš moje diea a prinesieš ho sem.
{130620}{130642}Nehıb sa.
{130713}{130793}Duke, Robert je màtvy.
{130796}{130923}Viem o tvojej dohode,|no iadne peniaze nikdy neuvidíš.
{130925}{130986}Je po všetkom.
{130988}{131051}Daj mi to diea.
{131144}{131221}- Daj mi dve minúty.
{131704}{131785}Take je navdy po peniazoch.
{132085}{132212}- Èo odo mòa chceš?|- Dnes veèer môeme dosta toho bastarda.
{132214}{132354}Dnes veèer môeme posla|Jasona Voorheesa do pekla na veèné èasy.
{132357}{132411}- Na to nepotrebuješ mòa.|- Ale áno...
{132439}{132458}Potrebujem !
{132666}{132741}Jedine tak môe by Voorhees|znovuzrodenı...
{132746}{132823}...a iba Voorhees ho môe zabi.
{132826}{132853}S tımto!
{132857}{132935}Nie. Nevystavím svoje diea|ïalšiemu nebezpeèenstvu.
{132941}{133049}Navdy budeš ohrozená,|kım nebude Jason màtvy.
{133052}{133214}Neprestane a h¾ada, kım a nedostane,|kım nebude znovuzrodenı.
{133217}{133282}A potom a zabije...
{133285}{133331}... aj tvoje diea.
{133370}{133528}Ak chceš, aby to skonèilo,|aby bolo diea v bezpeèí...
{133528}{133587}... tak to ukonèi hneï teraz.
{133589}{133710}Predtım,  ako zomrú ïalší ¾udia,|tak ako tvoji priatelia,|tak ako tvoja matka.
{133729}{133803}Pretoe pokia¾ ho nezabiješ...
{133848}{133925}...neskonèí to.
{135167}{135237}Ach, ty tu spíš?
{135380}{135472}Mm? To by mohol by Steven.
{135475}{135545}Teraz Jason prestúpi do nového tela.
{135555}{135621}Nemôeš veri nikomu.
{135625}{135707}- Steven to nemôe by.|- Ktoko¾vek. Rozumieš?
{135760}{135809}Duke!
{135869}{135924}- Jessica?
{135929}{135965}- Ed?|- Nie!
{136009}{136082}Zabi ho! Urob to!
{136087}{136146}Ed, si to naozaj ty?
{136146}{136191}- Samozrejme.|- Zostaò tam!
{136191}{136256}- Daj mi ten nô.|- Myslela som, e si màtvy.
{136261}{136318}- Mılila si sa.|- Nechoï blišie.
{136322}{136357}- Zabi ho!|- Nemôem!
{136361}{136418}- Oh...|- Kurva!
{136424}{136497}- Choï do pekla od nej, Ed!
{136650}{136720}- Duke, èo mám robi?|- Zabi ich obidvoch!
{136725}{136775}- Nie!|- Urob to, inak zomrieš!
{136780}{136849}Jessica, daj mi ten nô.
{136854}{136897}- Nepribliuj sa!|- Jessica!
{137021}{137045}Ach!
{137121}{137143}Do riti !
{137636}{137703}Zmizni! Vypadni od nej!
{137750}{137784}Steven!
{138629}{138673}Kde je?!
{138678}{138735}- Neviem!
{139030}{139084}Duke?!
{139086}{139129}U idem.
{139134}{139220}- Pomôem ti.|- Podaj mi ruku.
{139250}{139343}No tak!
{139550}{139578}Tu!
{139657}{139699}Pohni!
{139919}{139976}- Kde je tá dıka?|- Je pod stolom.
{139979}{140060}- Dobre, zober ju!
{140074}{140151}Nemyslím. Ach, boe.
{140163}{140211}- Èo to robí?|- Neviem.
{140211}{140295}Duke, tá èas o|Voorheesovom znovuzrodení...
{140295}{140345}- ...tıka sa to iba ivej eny?|- Nie.
{140349}{140449}Potom sa to práve stalo|v prízemí s Jessicinou matkou.
{140566}{140622}- Svätá matka boia.
{140841}{140930}Rıchlo, dıku.
{140934}{140972}Pomô jej!
{140978}{141017}Zober tú prekliatu dıku!
{141021}{141075}- Vstávaj, tak vstaò!|- OK.
{141111}{141156}- Nemôem!|- Jessica!
{141200}{141282}Ty sukin syn. Pamätáš si na mòa ?
{141533}{141561}- Zober tú dıku!
{141684}{141780}Dnes veèer, môj priate¾...
{141786}{141833}Jessica!
{141836}{141888}...zdochneš!
{141959}{141997}Duke!
{142073}{142113}Ach, boe!
{142439}{142523}Vypadni od nej,|skurvysyn!
{143530}{143566}Nie!
{144546}{144609}Ach!
{144852}{144888}Nie.
{147333}{147409}Choï ... do ... pekla !
{147413}{147446}Agh!
{148123}{148160}Nie! Nie!
{148196}{148253}Nie!
