{1}{20}29.970
{50}{300}Preloil a upravil : Martin| etmare@atlas.cz
{3595}{3673}Do riti !
{4432}{4491}Bingo.
{8411}{8447}Do èerta !
{11895}{11955}Strie¾aj!
{12839}{12891}Prichádza!
{12947}{12999}- Vyskoè!
{13187}{13215}Áno!
{13430}{13456}Áno!
{13935}{14020}Nezdie¾am vašu rados...
{14034}{14147}- Dobrá práca, agentka Marcusová.|- Ïakujem.
{14150}{14265}Dobrá trefa, Mahoney.|Teraz vyèisti všetky tie sraèky, èo?
{14630}{14720}PIATOK 13 - part 9
{14720}{14900}PIATOK 13 - part 9|JASON IDE DO PEKLA
{14900}{15000}PIATOK 13 - part 9|JASON IDE DO PEKLA|Poslednı piatok
{15333}{15397}ID, prosím.
{15944}{16004}V poriadku, pane.
{17123}{17210}Meno - Voorhees, Jason.
{17210}{17323}Toto je iba na oèi. Táto páska|je striktne pre internú distribúciu.
{17327}{17393}Ak ste poèúvali viete, e znièi to môe|iba C-4 alebo nieèo silnejšie.
{17396}{17494}Ak nie - máte naozaj problém!
{18203}{18266}Ooh...
{18303}{18334}Boe !
{18688}{18781}Máme ve¾kého kaukazského samca ...
{18783}{18934}...s masívnou stratou tkaniva,|spôsobenou extrémne silnou trhavinou.
{18938}{19083}Váha - povedal by som 230, snáï... 240.
{19085}{19264}Tretí stupeò popálenín|na 65% predchádzajúceho trupu.
{19266}{19421}Prvı a druhı|na... neskoršom trupe.
{19993}{20088}K tej traumatickej explózii...
{20100}{20191}...subjekt je obe ...
{20194}{20265}...viacnásobnıch...
{20267}{20323}...strelnıch rán.
{20479}{20536}Na prvı poh¾ad, dá sa poveda...